### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by tim-peterson** [Ziptastic/ziptastic-jquery-plugin#14]
Currently **ziptastic** blows up my https certification on my site b/c the request is an http:// and not an https:// request:

```
$.getJSON('http://zip.elevenbasetwo.com/v2/US/' + zip);
```

Are there any plans for **ziptastic** to be served up from a https:// site? This is critical b/c requesting one's zip code is sensitive information and I'd assume most sites wanting to use this plugin would be https:// sites.

**Comment by vijapandey** [comment]
Hi Friends ,
We are facing " javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target" by using https://zip.getziptastic.com/v2/US/10001 .Please provide solution for this

**Comment by daspecster** [comment]
Hello!
Thanks for your interest in Ziptastic!
The Certs we are using are from Comodo which may not be considered valid
since they're a smaller SSL provider.

I did find some potential solutions here...
http://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find

Once we have money for better certificates we will install them right away!

Thanks again! Let me know if this helps solve your problem.
You can sign up to our mailing list to be notified when we upgrade our
certificates.
Mailing List: http://eepurl.com/bbtBzP


On Tue, Feb 17, 2015 at 9:19 AM, vijapandey <notifications@github.com>
wrote:

> Hi Friends ,
> We are facing " javax.net.ssl.SSLHandshakeException:
> sun.security.validator.ValidatorException: PKIX path building failed:
> sun.security.provider.certpath.SunCertPathBuilderException: unable to find
> valid certification path to requested target" by using
> https://zip.getziptastic.com/v2/US/10001 .Please provide solution for
> this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daspecster/ziptastic-jquery-plugin/issues/14#issuecomment-74673934>
> .
>



-- 
Tom Schultz
